version: '2'
services:
  web:
    build: .
    entrypoint: ["lib/docker-entrypoint.sh"]
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    volumes:
      - .:/app
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    depends_on:
      - operationcode-psql
      - redis
    env_file:
      - .env

  bundle:
    image: operationcodebackend_web
    command: echo bundle data container
    volumes:
      - /bundle

  operationcode-psql:
    image: postgres
    env_file:
      - .env

  redis:
    image: redis:latest

  sidekiq:
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - .:/app
    volumes_from:
      - bundle
    depends_on:
      - operationcode-psql
      - redis
    env_file:
      - .env
