# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  jwt_secret: 'super random key'
  jwt_expiration_hours: 24
  py_bot_auth_key: 'some random key'
  secret_key_base: 5d44826022fd9ef943fa7d5dcaf76722893b63e264fd8b3d22174992a001ed0bd8bb91131928d9ab2d25b6eccce54ebca320a7676942d05ae3defe96e2f04346

test:
  jwt_secret: 'super random test key'
  jwt_expiration_hours: 24
  py_bot_auth_key: 'some random key'
  secret_key_base: 5a8beb5fc0bf57a8641d0720091190160f725c9063192cf33a0389524ed1dab63527880287c88fd6a3a3b42435cbc0693ce2fec233052bfe6648350c1d0df971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  jwt_secret: <%= ENV['JWT_SECRET_KEY'] %>
  jwt_expiration_hours: 6
  py_bot_auth_key: <%= ENV['PY_BOT_AUTH_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
